steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east4-docker.pkg.dev/qwiklabs-gcp-01-956ae2f30263/my-repository/hello-cloudbuild:v2.0', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east4-docker.pkg.dev/qwiklabs-gcp-01-956ae2f30263/my-repository/hello-cloudbuild:v2.0']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['get-credentials', 'hello-cluster', '--zone', 'us-east4-c']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'dev/deployment.yaml', '-n', 'dev']
