apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
#<<<<<<< HEAD
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-01-956ae2f30263/my-repository/hello-cloudbuild:v2.0
#=======
#        image: us-east4-docker.pkg.dev/qwiklabs-gcp-01-956ae2f30263/my-repository/hello-app:v1.0
#>>>>>>> dev
        ports:
        - containerPort: 8080
